### ISSUE TITLE
Can we have a voting system please?

### ISSUE THREAD

**Issue by Elevator-lady** [kcgidw/fao#7]
Hi. Thanks for putting Fake Artist online. We play it at home with good ol' pen and paper but searched this version up when the covid-19 lockdown began. We'd love to play it across households, but we can't think how best to vote for the Fake Artist.

Would it be possible to display the player names and colours throughout the game, rather than just having it as an optional popup, and then use this same list when the two rounds have finished to create a poll to vote for the Fake Artist?

If the Fake Artist is identified, it would be great to then have a text box where they could type in their guess as to what the drawing is of. I suppose maybe then everyone could get a prompt to say if they were correct or not, which would disappear when the first person responded. Then there could be a display of what the category and object actually were, and the points total for the rounds played so far.

...I ask this in complete ignorance of how much work this might entail! But it would be so great if you could do this so we can play with our friends locked-down across town. :-)

**Comment by kcgidw** [comment]
Hi, thanks for reaching out! Unfortunately a voting system seems pretty far off at the moment, even though it's definitely been on my own mind - sometimes even I'd love to have it.

Still, it would require a lot of additional logic and mulling over the UI design... not to mention that every system I add to the game is another restriction against someone's house rules.

For now, video-conferencing or voice-conferencing (Facebook, Hangouts, Zoom, Discord) seems like it would be your best bet.
